server.port = 8081

spring.application.name=TasQ
spring.datasource.url=jdbc:postgresql://localhost:5432/TasQ
spring.datasource.username=postgres
spring.datasource.password=0305

spring.jpa.hibernate.ddl-auto=update
